# FILE:    netlify.toml
# VERSION: v21
# UPDATED: 2026-06-09
# CHANGES: v21: Points to index-v21.html. Fixed transcription field names to camelCase.

[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from   = "/.netlify/functions/*"
  to     = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from   = "/"
  to     = "/index-v21.html"
  status = 200
